region: 'us-east-1'

handler: 'app/handler.logpull'

schedule:
  name: 'fiveminutes'
  expression: 'rate(5 minutes)'

lambda:
  functionName: 'cloudflare-logs'

  # This is an example role. You have to create your own
  # http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html#roles-creatingrole-service-console
  role: 'arn:aws:iam::123456789012:policy/cloudflare-logs-role'
  # The execution environment for the Lambda function.
  execution:
    runtime: 'nodejs8.10'
    timeoutSeconds: 60
    memorySizeMB: 512

runtime:
  # you can define the interval for polling new logs. You'll need to change the interval below 
  # and the schedule expression above. interval must match the rate defined in schedule.expression.
  # For example, for 'rate(5 minutes)', interval is 5
  interval: 5
  cf:
    # These are example credentials.
    authKey: 79bfb07774419f2dce2ae7a4f391d72207502
    authEmail: frank@example.com
    orgId: aba996ecd4306f7775a1f9a2f982008a
